website/music/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail,name='detail'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('music.urls')),
]

website/music/models.py
from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)
	def __str__(self):
		return self.album_title + "-" + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	def __str__(self):
		return self.song_title

website/music/views.py
from django.shortcuts import render,get_object_or_404
from .models import Album
# Create your views here.
def index(request):
	albums = Album.objects.all()
	return render(request,'music/index.html',{'albums':albums})

def detail(request, pk):
	album = get_object_or_404(Album,pk=pk)
	return render(request,'music/detail.html',{'album':album})

website/music/templates/music/detail.html
<img src="{{album.album_logo}">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>
<ul>
	{% for song in album.song_set.all %}
		<li>{{song.song_title}}.{{son.file_type}}</li>
	{%endfor%}
</ul>

website/music/templates/music/index.html
<h3>Here are my all albums</h3>
<ul>
	{% for album in albums %}
	<li><a href="/music/{{ album.id }}/">{{ album.album_title }}</a></li>
	{%endfor%}
</ul>